language: node_js
node_js:
<<<<<<< HEAD
 - 5
 - 4
notifications:
  slack: andela:VM5JOkV0tR1M1X8BfCMgMusY
services:
 - MongoDB
after_script: 
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
=======
 - "stable"

notifications:
  slack: andela:VM5JOkV0tR1M1X8BfCMgMusY
>>>>>>> 9d3f59caf9f6a1b9b8718fac39e8908fde5878b2
